### ISSUE TITLE
Uploading phonebook does not work anymore

### ISSUE THREAD

**Issue by derwok** [andig/carddav2fb#108]
I'm on master branch latest commit 49488be566a8374d65c7deb8c58c1660730c420b

Uploading phonebook does not work (anymore) here.
The script runs fine til the point where uploading of phonebook takes place.
Then it stalls - for almost a minunte no output on console.
Then `Getötet` shows up in the console.
I listed the PHP version afterwards.

```
Detaching and uploading image(s)
 138/138 [============================] 100%Uploaded/refreshed 0 of 93 image file(s)
Getötet
pi ~/bin/carddav2fb$php --version
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by churchy16** [comment]
I have the same problem.
To me it looks like Converter.php is broken after the last commit (endless loop).

**Comment by andig** [comment]
Could you do a quick check which function in https://github.com/andig/carddav2fb/commit/49488be566a8374d65c7deb8c58c1660730c420b#diff-dbde8f29978050cd1b346360ada9e3b9 contains the endless loop? I guess its one of the `getPhone` or similiar. Otherwise, go back 1 commit for the time being and I'll fix this later.

Sorry for the hassle, but the cleanup was necessary :/

**Comment by churchy16** [comment]
The infinite loop starts in function "convert" in the line
`while (count($this->numbers)) {`
this count always stays the same (2) in my test conversion with one address book entry containing 2 phone numbers.

**Comment by andig** [comment]
Thanks- I‘ve overkooked that one and will convert to foreach. Had to get rid of the index-based logic. 

Viele Grüße,
Andreas

**Comment by andig** [comment]
I've pushed another commit that should take care of this problem. Root cause is that the current code was using highly implicit, non-obvious parameter passing. I've changed this by making the function parameters explicit. This introduces a behaviour change. Before, contacts with >9 phone numbers were split into multiple contacts. Now, phone numbers beyond 9 are ignored. If this is not acceptable We need to go back and find a better solution.

**Comment by andig** [comment]
Note: I've also just pushed 2f97f5830f0fbccecc53fb485008854379a603ed which makes additional changes to the converter. To get rid of the index-based multi-nested-loop handling I've also change the `addEmail` function. To be honest, I can't say if it still does the same thing as before, so please take a careful look.

Long story short: the existing code was too convoluted and hard to change, especially being without any automated test cases.
