### ISSUE TITLE
Upload fails with 'Upload faild'

### ISSUE THREAD

**Issue by L0ric0** [andig/carddav2fb#165]
in src/functions.php:479 the error is thrown even when the fritzbox return contains `FRITZ!Box telephone book restored` 

Maybe add to the readme that the fritzbox has to be set to german or add alternatives

**Comment by andig** [comment]
Fixed via https://github.com/andig/carddav2fb/commit/c39cb321cbdeecba7d0ecb91878863d9f69445ca

**Comment by blacksenator** [comment]
@L0ric0 Could you kindly check out what the English success message for the backgroundimage upload is. We are currently only checking for the German text.

**Comment by L0ric0** [comment]
will do when i'm home from the holidays

**Comment by blacksenator** [comment]
@L0ric0 have you had a chance to look?

**Comment by L0ric0** [comment]
sorry i forgot. do you have a curl command or something of the like as i don't use background images

**Comment by blacksenator** [comment]
There is a description [here](https://en.avm.de/service/fritzfon/fritzfon-c5/knowledge-base/publication/show/300_Adding-background-images-and-contact-pictures/) in paragraph **3** or otherwise the body for the guzzle-request [here](https://github.com/andig/carddav2fb/blob/d0fe8e087e09ce6e955fa789618ba528b4b6c6c5/src/FritzBox/BackgroundImage.php#L151)

**Comment by blacksenator** [comment]
Solved with #195
